# templates/configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ocne-ha-config.fullname" . }}-check.sh
data:
  check.sh: |-
{{ tpl .Values.checkScript $ | indent 4 }}
  keepalived.tmpl: |-
{{ tpl .Values.keepalived.template $ | indent 4 }}
  nginx.tmpl: |-
{{ tpl .Values.nginx.template $ | indent 4 }}
