apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ocne-ha-config.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ocne-ha-config.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ocne-ha-config.serviceAccountName" . }}
  namespace: default
  labels:
    {{- include "ocne-ha-config.labels" . | nindent 4 }}
rules:
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ocne-ha-config.serviceAccountName" . }}
  namespace: default
  labels:
    {{- include "ocne-ha-config.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "ocne-ha-config.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "ocne-ha-config.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
