annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Adds backwards compatibility with Kubernetes 1.20 by selecting the HPA apiVersion of autoscaling/v2beta2
      links:
        - name: Github PR
          url: https://github.com/oauth2-proxy/manifests/pull/364
apiVersion: v2
appVersion: 7.12.0
description: A reverse proxy that provides authentication with Google, Github or other providers
home: https://oauth2-proxy.github.io/oauth2-proxy/
keywords:
  - kubernetes
  - oauth
  - oauth2
  - authentication
  - google
  - github
  - redis
kubeVersion: '>= 1.26.0 < 1.34.0'
maintainers:
  - email: pierluigi.lenoci@gmail.com
    name: pierluigilenoci
  - email: jan@larwig.com
    name: tuunit
  - email: joel.speed@hotmail.co.uk
    name: JoelSpeed
name: oauth2-proxy
sources:
  - https://github.com/oauth2-proxy/oauth2-proxy
  - https://github.com/oauth2-proxy/manifests
version: 7.12.0
icon: icons/OAuth2_Proxy_horizontal.svg
