apiVersion: v2
name: ovirt-csi-driver
description: Implementation of a CSI driver for oVirt.
type: application
version: 4.21.0
appVersion: "4.21.0"
icon: icons/kubernetes-logo.svg
kubeVersion: '>= 1.30.0 < 1.34.0'
