apiVersion: v2
appVersion: 3.5.0
dependencies: []
description: Fluent Operator provides great flexibility in building a logging layer based on Fluent Bit and Fluentd.
home: https://www.fluentd.org/
icon: icons/fluent-operator-icon.svg
keywords:
  - logging
  - fluent-bit
  - fluentd
  - operator
maintainers:
  - email: dehaocheng@kubesphere.io
    name: wenchajun
name: fluent-operator
sources:
  - https://github.com/fluent/fluent-operator
version: 3.5.0
kubeVersion: '>= 1.26.0 < 1.34.0'
