annotations:
  artifacthub.io/changes: |
    - Update Ingress-Nginx version controller-v1.14.0
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: 1.14.0
description: Ingress controller for Kubernetes using NGINX as a reverse proxy and load balancer
home: https://github.com/kubernetes/ingress-nginx
icon: icons/500px-Nginx_logo.svg.png
keywords:
  - ingress
  - nginx
kubeVersion: '>= 1.30.0 < 1.34.0'
maintainers:
  - name: cpanato
  - name: Gacko
  - name: strongjz
  - name: tao12345666333
name: ingress-nginx
sources:
  - https://github.com/kubernetes/ingress-nginx
version: 1.14.0
